name: Deploy App with multi-containers
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and run tests
        run: |
          docker build -t yl238/multi-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true yl238/multi-test npm test -- --coverage
      - name: Build docker containers
        run: |
          docker build -t yl238/multi-client ./client
          docker build -t yl238/multi-nginx ./nginx
          docker build -t yl238/multi-server ./server
          docker build -t yl238/multi-worker ./worker
      - name: Push to Dockerhub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push yl238/multi-client
          docker push yl238/multi-nginx
          docker push yl238/multi-server
          docker push yl238/multi-worker


      # - name: Generate deployment package
      #   run: zip -r deploy.zip . -x '*.git*'
 
      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v18
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #     application_name: docker-multi
      #     environment_name: Dockermulti-env
      #     existing_bucket_name: elasticbeanstalk-eu-west-1-925776718773
      #     region: eu-west-1
      #     version_label: ${{ github.sha }}
      #     deployment_package: deploy.zip
